SP.Web/Areas/Student/Controllers/StdAdmissionController.cs
using SP.Data;
using SP.Data.Academic;
using SP.Data.Models;
using SP.Data.session;
using SP.Data.Student;
using SP.Web.Areas.Student.Models;
using SP.Web.Components.Academic;
using SP.Web.Components.Student;
using System;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;

namespace SP.Web.Areas.Student.Controllers
{
    public class StdAdmissionController : Controller
    {

        #region obj
        //===Use when Student Edit Process Running==
        string StudentIdForEditSessionName { get => "StudentIdForEditSessionName"; }
        public ActionResult RedirectToAfterEdit { get => RedirectToAction("Index", "StdListViews"); }

        //==Objects==
        //Db
        private SP_DataEntities db = new SP_DataEntities();

        //Class/ Sec /Session
        SessionUtils sessionUtils = new SessionUtils();
        ClassTools _classTools = new ClassTools();
        SectionComponent _sectionComponent = new SectionComponent();
        ClassComponent classComponent = new ClassComponent();

        //Student
        StdAdmissionUtils stdAdmissionUtils = new StdAdmissionUtils();
        StudentTools studentTools = new StudentTools();
        StdAdmissionHttpSessionModels _stdAdmissionHttpSessionModels = new StdAdmissionHttpSessionModels();
        #endregion

        #region ====== Student Details ======

        #region <----- Create---- ->

        [ActionName("StdDetailsCreate")]
        public ActionResult StdDetailsCreate()
        {
            //Get the Session Storage  
            Std_Details stdentDetails = HttpContextSessionTools.GetHttpContextSessionObject<Std_Details>(_stdAdmissionHttpSessionModels._sStdDetails);

            //DropDownList  Data Select
            var caste = stdentDetails.ISValidObject() ? stdentDetails.CasteID.ConvertObjectToString() : "";
            var disability = stdentDetails.ISValidObject() ? stdentDetails.DisabilityID.ConvertObjectToString() : "";
            var economicalSatus = stdentDetails.ISValidObject() ? stdentDetails.EconomicalSatusID.ConvertObjectToString() : "";
            var nationality = stdentDetails.ISValidObject() ? stdentDetails.NationalityID.ConvertObjectToString() : "";
            var religion = stdentDetails.ISValidObject() ? stdentDetails.ReligionID.ConvertObjectToString() : "";
            var supportingDoc = stdentDetails.ISValidObject() ? stdentDetails.SupportingDocID.ConvertObjectToString() : "";
            var subCasteNameId = stdentDetails.ISValidObject() ? stdentDetails.SubCasteID.ConvertObjectToString() : "";

            //DropDownListBox
            ViewBag.CasteID = new SelectList(db.Castes, "Id", "CasteName", caste);
            ViewBag.SubCasteID = new SelectList(db.SubCastes, "Id", "SubCasteName", subCasteNameId);
            ViewBag.DisabilityID = new SelectList(db.DisabilityTypes, "Id", "CatagoryName", disability);
            ViewBag.EconomicalSatusID = new SelectList(db.EconomicalStatus, "Id", "EconomicalStatusName", economicalSatus);
            ViewBag.NationalityID = new SelectList(db.Nationalities, "Id", "NationalityName", nationality);
            ViewBag.ReligionID = new SelectList(db.Religions, "Id", "Religion1", religion);
            ViewBag.SupportingDocID = new SelectList(db.SupportingDocs, "Id", "DocumentName", supportingDoc);

            //Return
            return PartialView(stdentDetails);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult StdDetailsCreate([Bind(Include = "ID,StudentID,SessionID,StudentName,Gender,DOB,Photo,CasteID,SubCasteID,ReligionID,NationalityID,EconomicalSatusID,EconomicalStatusNo,SupportingDocID,IsPCDisability,PCPer,DisabilityID")] Std_Details std_Details, System.Web.HttpPostedFileBase StudentImage, string btnPrevious, string btnNext, string btnReset)
        {
            string imgMessge = "";
            //Student Image
            #region Image
            if (StudentImage != null)
            {
                if (StudentImage.IsImage(1048576, out imgMessge))
                {
                    std_Details.Photo = new byte[StudentImage.ContentLength];
                    StudentImage.InputStream.Read(std_Details.Photo, 0, StudentImage.ContentLength);
                }
                else
                {
                    ModelState.AddModelError("Photo", imgMessge);
                }
            }

            #endregion

            if (ModelState.IsValid)
            {

                //Create Session Storage and  Store data
                HttpContextSessionTools.CreateHttpContextSession<Std_Details>(_stdAdmissionHttpSessionModels._sStdDetails, std_Details);

                //WIzered Process
                return CreateStepWizered("StdDetailsCreate", btnPrevious, btnNext, btnReset);
            }

            //DropDownList
            ViewBag.CasteID = new SelectList(db.Castes, "Id", "CasteName", std_Details.CasteID);
            ViewBag.SubCasteID = new SelectList(db.SubCastes, "Id", "SubCasteName", std_Details.SubCasteID);
            ViewBag.DisabilityID = new SelectList(db.DisabilityTypes, "Id", "CatagoryName", std_Details.DisabilityID);
            ViewBag.EconomicalSatusID = new SelectList(db.EconomicalStatus, "Id", "EconomicalStatusName", std_Details.EconomicalSatusID);
            ViewBag.NationalityID = new SelectList(db.Nationalities, "Id", "NationalityName", std_Details.NationalityID);
            ViewBag.ReligionID = new SelectList(db.Religions, "Id", "Religion1", std_Details.ReligionID);
            ViewBag.SupportingDocID = new SelectList(db.SupportingDocs, "Id", "DocumentName", std_Details.SupportingDocID);

            return PartialView(std_Details);
        }

        #endregion

        #region <----- Edit ---->

        [ActionName("StdDetailsEdit")]
        public async Task<ActionResult> StdDetailsEdit(Guid? id)
        {
            if (id == null)
            {
                //Get Student Id
                id = HttpContextSessionTools.GetHttpContextSessionObject<Guid>(StudentIdForEditSessionName);
            }

            //Store student Id in session
            HttpContextSessionTools.CreateHttpContextSession<Guid>(StudentIdForEditSessionName, id.ConvertToGuid());

            //Check Id
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Std_Details std_Details = await db.Std_Details.FindAsync(id);
            if (std_Details == null)
            {
                return HttpNotFound();
            }

            //DropDownList
            ViewBag.CasteID = new SelectList(db.Castes, "Id", "CasteName", std_Details.CasteID);
            ViewBag.DisabilityID = new SelectList(db.DisabilityTypes, "Id", "CatagoryName", std_Details.DisabilityID);
            ViewBag.EconomicalSatusID = new SelectList(db.EconomicalStatus, "Id", "EconomicalStatusName", std_Details.EconomicalSatusID);
            ViewBag.NationalityID = new SelectList(db.Nationalities, "Id", "NationalityName", std_Details.NationalityID);
            ViewBag.ReligionID = new SelectList(db.Religions, "Id", "Religion1", std_Details.ReligionID);
            ViewBag.SubCasteID = new SelectList(db.SubCastes, "Id", "SubCasteName", std_Details.SubCasteID);
            ViewBag.SupportingDocID = new SelectList(db.SupportingDocs, "Id", "DocumentName", std_Details.SupportingDocID);

            //Return
            return View(std_Details);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> StdDetailsEdit([Bind(Include = "StudentID,SessionID,StudentName,Gender,DOB,Photo,CasteID,SubCasteID,ReligionID,NationalityID,EconomicalSatusID,EconomicalStatusNo,SupportingDocID,IsPCDisability,PCPer,DisabilityID")] Std_Details std_Details, System.Web.HttpPostedFileBase StudentImage)
        {
            string imgMessge = "";
            #region Image
            if (StudentImage != null)
            {
                if (StudentImage.IsImage(1048576, out imgMessge))
                {
                    std_Details.Photo = new byte[StudentImage.ContentLength];
                    StudentImage.InputStream.Read(std_Details.Photo, 0, StudentImage.ContentLength);
                }
                else
                {
                    ModelState.AddModelError("Photo", imgMessge);
                }
            }
            else
            {
                //var _dataDetails= db.Std_Details.Find(std_Details.StudentID);
                // std_Details.Photo = _dataDetails.Photo;
            }
            #endregion

            //Update
            if (ModelState.IsValid)
            {
                db.Entry(std_Details).State = EntityState.Modified;
                await db.SaveChangesAsync();
                return RedirectToAfterEdit;
            }

            //DropDownList
            ViewBag.CasteID = new SelectList(db.Castes, "Id", "CasteName", std_Details.CasteID);
            ViewBag.DisabilityID = new SelectList(db.DisabilityTypes, "Id", "CatagoryName", std_Details.DisabilityID);
            ViewBag.EconomicalSatusID = new SelectList(db.EconomicalStatus, "Id", "EconomicalStatusName", std_Details.EconomicalSatusID);
            ViewBag.NationalityID = new SelectList(db.Nationalities, "Id", "NationalityName", std_Details.NationalityID);
            ViewBag.ReligionID = new SelectList(db.Religions, "Id", "Religion1", std_Details.ReligionID);
            ViewBag.SubCasteID = new SelectList(db.SubCastes, "Id", "SubCasteName", std_Details.SubCasteID);
            ViewBag.SupportingDocID = new SelectList(db.SupportingDocs, "Id", "DocumentName", std_Details.SupportingDocID);

            //Return
            return View(std_Details);
        }

        #endregion

        #endregion

        #region ====== - ParentsDetails======

        #region <----- Create ----->

        // GET: Student/Std_ParentsDetails/Create

SP.Web/Areas/Student/Views/StdAdmission/StdBankEdit.cshtml
@model SP.Data.Models.Std_BankDetails
@using SP.Web.Infrastructure.Layout

@{
    ViewBag.Title = "Student Bank Details";
    ViewBag.Icon = "fa fa-bank";
    ViewBag.Description = "Student Bank Details";
    Layout = LayoutIStruct._StudentEditLayout;
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="container-fluid">

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        @Html.HiddenFor(model => model.ID)
        @Html.HiddenFor(model => model.StudentId)

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.BranchDetailsID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("BranchDetailsID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.BranchDetailsID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.AccountNo, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.AccountNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.AccountHolderName, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.AccountHolderName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AccountHolderName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            <div class="col-md-offset-2 ">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

SP.Web/Areas/Student/Views/StdAdmission/StdDetailsEdit.cshtml
@model SP.Data.Models.Std_Details
@using SP.Data;

@{
    /**/

    ViewBag.Title = "Student";
    Layout =SP.Web.Infrastructure.Layout.LayoutIStruct._StudentEditLayout;
}

@using (Html.BeginForm("StdDetailsEdit", "StdAdmission", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="container-fluid row ">

        @Html.HiddenFor(model => model.SessionID)
        @Html.HiddenFor(model => model.StudentID)



        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.StudentName, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.StudentName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.StudentName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.Gender, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownListFor(model => model.Gender, new List<SelectListItem>() { new SelectListItem() { Text = "MALE", Value = "MALE" },
              new SelectListItem() { Text = "FEMALE", Value = "FEMALE" },
               new SelectListItem() { Text = "OTHERS", Value = "OTHERS" } },
               htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Gender, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.DOB, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.DOB, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.DOB, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.CasteID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("CasteID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.CasteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.SubCasteID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("SubCasteID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SubCasteID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.ReligionID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("ReligionID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ReligionID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.NationalityID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("NationalityID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.NationalityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.EconomicalSatusID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("EconomicalSatusID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.EconomicalSatusID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.EconomicalStatusNo, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.EconomicalStatusNo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EconomicalStatusNo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.SupportingDocID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("SupportingDocID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.SupportingDocID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group">
            @Html.LabelFor(model => model.IsPCDisability, htmlAttributes: new { @class = "control-label" })
            <div class="">
                <div class="checkbox">
                    @Html.CheckBoxFor(model => model.IsPCDisability, new { @class = "form-control", @ng_model = "hideIsPCDisability" })
                    @Html.ValidationMessageFor(model => model.IsPCDisability, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="col-md-6 form-group" ng-show='hideIsPCDisability'>
            @Html.LabelFor(model => model.PCPer, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.EditorFor(model => model.PCPer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PCPer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group" ng-show='hideIsPCDisability'>
            @Html.LabelFor(model => model.DisabilityID, htmlAttributes: new { @class = "control-label" })
            <div class="">
                @Html.DropDownList("DisabilityID", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.DisabilityID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-6 form-group text-center">
            @Html.LabelFor(model => model.Photo, htmlAttributes: new { @class = "control-label" })<br />

            <div class="">
                @{
                    string imageSrc = "";
                    System_Web_UI_WebControls_Imager ss = new System_Web_UI_WebControls_Imager();
                    if (Model.Photo != null)
                    {
                        imageSrc = ss.byteArrayToWebImage((Model.Photo)).ImageUrl;
                    }
                }
                <img id="_ImgStudentImage" src="@imageSrc" class="w3-image img-bordered w3-border-brown text-center" style="height:100px;width:100px" alt="Student" />
                @Html.TextBox("StudentImage", "", new { id = "StudentImage", onchange = "ImagePreviewFrominputFile(this,'_ImgStudentImage')", @class = "form-control", type = "file" })
                @Html.ValidationMessageFor(model => model.Photo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="col-md-12 form-group text-right">
            <div class="col-md-offset-2 ">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>

}

@* Image Preview js
    use :ImagePreviewFrominputFile(this,imagename)*@
<script src="~/wwwroot/Script/ImagePreview.js"></script>

SP.Web/Areas/Student/Views/StdAdmission/StdParentsDetailsCreate.cshtml
@model SP.Data.Models.Std_ParentsDetails

@{
    /**/

    ViewBag.Title = "";
    Layout = SP.Web.Infrastructure.Layout.LayoutIStruct._AdminPanelLayout;
}
@using (Html.BeginForm("StdParentsDetailsCreate", "StdAdmission", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="card card-info card-outline direct-chat-info">
        <div class="card-header">
            <h3 class="card-title"><br /></h3>
            <div class="card-tools">
                <button class="btn btn-tool" type="button" data-widget="collapse">
                    <i class="fa fa-minus"></i>
                </button>
                <button class="btn btn-tool" type="button" data-widget="remove">
                    <i class="fa fa-times"></i>
                </button>
            </div>

            @*====Header====*@
            @Html.Partial("_AdmissionBreadCrumb", new SP.Web.Areas.Student.Models.StdAdmissionToolsBerModels
        {
            StudentParentDetails = true
        })


            @*====//Header====*@
        </div>

        <!-- /.card-header -->
        <div class="card-body">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="row">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FatherName, htmlAttributes: new { @class = "control-label" })

                    <div class="">
                        @Html.EditorFor(model => model.FatherName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FatherAddress, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.FatherAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherAddress, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FatherOccupation, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.FatherOccupation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherOccupation, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">
                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FatherAI, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.FatherAI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherAI, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FatherQualification, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.FatherQualification, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherQualification, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FatherContactNo, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.FatherContactNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherContactNo, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.FatherVoterId, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.FatherVoterId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.FatherVoterId, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.MotherName, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.MotherName, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherName, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.MotherAddress, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.MotherAddress, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherAddress, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row">

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.MotherOccupation, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.MotherOccupation, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherOccupation, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.MotherAI, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.MotherAI, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherAI, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-4">
                    @Html.LabelFor(model => model.MotherQualification, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.MotherQualification, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherQualification, "", new { @class = "text-danger" })
                    </div>
                </div>

            </div>

            <div class="row">
                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.MotherContactNo, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.MotherContactNo, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherContactNo, "", new { @class = "text-danger" })
                    </div>
                </div>

                <div class="form-group col-md-6">
                    @Html.LabelFor(model => model.MotherVoterId, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        @Html.EditorFor(model => model.MotherVoterId, new { htmlAttributes = new { @class = "form-control" } })
                        @Html.ValidationMessageFor(model => model.MotherVoterId, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="row text-center">
                <div class="form-group col-md-4 text-center">
                    @Html.LabelFor(model => model.FatherPhoto, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        <img id="_ImgFatherImage" class="w3-image img-bordered w3-border-brown text-center" style="height:100px;width:100px" src="#" alt="Father" />
                        @Html.TextBox("infFatherPhoto", "", new { id = "infFatherPhoto", onchange = "ImagePreviewFrominputFile(this,'_ImgFatherImage')", @class = "form-control", type = "file" })
                        @Html.ValidationMessageFor(model => model.FatherPhoto, "", new { @class = "text-danger" })
                    </div>
                </div>
                <div class="form-group col-md-4 text-center">
                    @Html.LabelFor(model => model.MotherPhoto, htmlAttributes: new { @class = "control-label" })
                    <div class="">
                        <img id="_ImgMotherImage" class="w3-image img-bordered w3-border-brown text-center" style="height:100px;width:100px" src="#" alt="Mother" />
                        @Html.TextBox("infMotherPhoto", "", new { id = "infMotherPhoto", onchange = "ImagePreviewFrominputFile(this,'_ImgMotherImage')", @class = "form-control", type = "file" })
                        @Html.ValidationMessageFor(model => model.MotherPhoto, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

        </div>
        <!-- /.card-body -->

        <div class="card-footer list-group-item col-md-12">
            @* left *@
            <button id="btnPrevious" name="btnPrevious" value="Previous" class="w3-btn w3-white w3-border w3-border-blue w3-round-large float-left col-md-2 disabled"><i class="fa fa-arrow-circle-o-left" disabled></i> Previous</button>
            @* right *@
            <button id="btnNext" name="btnNext" value="Next" class="w3-btn w3-white w3-border w3-border-green w3-round-large float-right col-md-2"> Next <i class="fa fa-arrow-circle-o-right"></i></button>&nbsp;&nbsp;
            <button id="btnReset" name="btnReset" value="Reset" class="w3-btn w3-white w3-border w3-border-green w3-round-large float-right col-md-2"> Reset <i class="fa fa-arrow-circle-o-right"></i></button>&nbsp;&nbsp;

        </div>
        <!-- /.card-footer-->
    </div>

}
@* Image Preview js
    use :ImagePreviewFrominputFile(this,imagename)*@
<script src="~/wwwroot/Script/ImagePreview.js"></script>