SP.Web/Areas/Subject/Controllers/SubjectsCombinationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Threading.Tasks;
using System.Net;
using System.Web;
using System.Web.Mvc;
using SP.Data.Models;
using SP.Web.Components.Subject;
using SP.Data.Academic.Tools;
using SP.Data.session;
using SP.Web.Components.Academic;
using SP.Data;
using SP.Data.Subject;

namespace SP.Web.Areas.Subject.Controllers
{
    public class SubjectsCombinationsController : Controller
    {
        #region obj
        private SP_DataEntities db = new SP_DataEntities();
        SubjectGroupComponent subjectGroupComponent = new SubjectGroupComponent();
        SubjectComponent subjectComponent = new SubjectComponent();
        SessionUtils sessionUtils = new SessionUtils();
        ClassComponent classComponent = new ClassComponent();
        SubjectCombinationTools subjectCombinationTools = new SubjectCombinationTools();
        #endregion


        public ActionResult Index()
        {
            return View();
        }

        #region mp
        public ActionResult MpSubCombinationIndex()
        {
            return RedirectToAction("MpSubCombCreate");
        }

        /// <summary>
        /// Mp Subject Combination Create
        /// </summary>
        /// <returns></returns>
        public async Task<ActionResult> MpSubCombCreate()
        {
          await  MpDropDownlistFill();
            return PartialView();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> MpSubCombCreate([Bind(Include = "GroupId,ClassId,SubjectId,SubjectType")]MPSubjectsCombination mPSubjectsCombination, string btnAddSubCombination)
        {
            if (btnAddSubCombination != null)
            {
                if (ModelState.IsValid)
                {
                    if (await subjectCombinationTools.IsDublicateMpSubjectsForCombinationAsync(mPSubjectsCombination.ClassId, mPSubjectsCombination.GroupId, mPSubjectsCombination.SubjectId))
                    {
                        ModelState.AddModelError("", "This Subject was already Present in same Group");
                    }

                    if (ModelState.IsValid)
                    {
                        db.MPSubjectsCombinations.Add(mPSubjectsCombination);
                        var IsResult = await db.SaveChangesAsync();
                    }
                }
            }

            //Fill Grid
            ViewBag.lstMpSubjectsCombinations = await subjectCombinationTools.GetMpSubjectsCombinationsAsync(mPSubjectsCombination.ClassId, mPSubjectsCombination.GroupId);

            //Fill DropDownList
            await  MpDropDownlistFill(mPSubjectsCombination.ClassId.ConvertObjectToString(), mPSubjectsCombination.SubjectId.ConvertObjectToString(), mPSubjectsCombination.GroupId.ConvertObjectToString());


            //return
            return PartialView(mPSubjectsCombination);
        }

        private async Task  MpDropDownlistFill(string ClassId_SelectValue = "", string SubjectId_SelectValue = "", string GroupId_SelectValue = "")
        {
            ViewBag.ClassId =await classComponent.CmbMpClassAsync(sessionUtils._gSessionIdVToX, ClassId_SelectValue);
            ViewBag.GroupId =await subjectGroupComponent.CmbSubjectGroupAsync(GroupId_SelectValue);

            //Subject
            ViewBag.SubjectId =await subjectComponent.CmbMpSubjectNotInCombinationSubjectAsync(sessionUtils._gSessionIdVToX, SubjectId_SelectValue);
        }

        [HttpGet]
        public async Task DeleteMpCombinationSubject(long SubID, long? GrpId)
        {
            if (GrpId.ISValidObject())
            {

            }
            MPSubjectsCombination mPSubjectsCombination = await db.MPSubjectsCombinations.FindAsync(SubID);
            db.MPSubjectsCombinations.Remove(mPSubjectsCombination);
            await db.SaveChangesAsync();
            //return Redirect(Request.Url.AbsoluteUri);
        } 
        #endregion

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

SP.Web/Areas/Subject/Views/SubjectsCombinations/HsSubjectCombination.cshtml
@model SP.Web.Models.HSSubjectsCombination
@using SP.Web.Infrastructure.AjaxStructure
@using SP.Data.Models
@{
    ViewBag.Title = "H.S. Subject Combination";
    Layout = null;
}
<div id="divHsSubjectCombinationUpdate">

    @using (Ajax.BeginForm(new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "divHsSubjectCombinationUpdate", LoadingElementId = AjaxFormIStruct.AjaxBeginFormLoading }))
    {
        @Html.AntiForgeryToken()

        <div class="container-fluid">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })

            <div class="form-group">
                @Html.LabelFor(model => model.GroupId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("GroupId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.StreamId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("StreamId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.StreamId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.SubjectId, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("SubjectId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>

            <div class="col-md-12 card card-info card-outline">
                <div class="card-header"><div class="card-title"></div></div>
                <div class="card-body">
                    <table class="table">
                        <thead>
                            <tr>
                                <th>
                                    @Html.DisplayNameFor(model => model.HSSubject.SubjectName)
                                </th>
                                <th><i class="fa fa-list-alt"></i></th>
                            </tr>
                        </thead>

                        <tbody>
                            @{
                                var subCombinationData = (List<HSSubjectsCombination>)ViewBag.lstMpSubjectsCombinations;
                                if (subCombinationData != null)
                                {

                                    foreach (var item in subCombinationData)
                                    {
                                        <tr>
                                            <td>
                                                @Html.DisplayFor(modelItem => item.HSSubject.SubjectName)
                                            </td>

                                            <td>
                                                @Html.ActionLink(" ", "DeleteMpCombinationSubject",
                                                     new { SubID = item.Id, GrpId = Model.GroupId }, new { @class = "fa fa-close w3-hover-text-red" })
                                            </td>
                                        </tr>
                                    }
                                }
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    }
</div>

SP.Web/Areas/Subject/Views/SubjectsCombinations/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using SP.Web.Infrastructure.Layout
@using SP.Web.Infrastructure.ControllerStructure.Subject
@{
    Layout = LayoutIStruct._AdminPanelLayout;
}


<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <!-- Custom Tabs -->
            <div class="card card-danger card-outline w3-card-4">
                <div class="card-header d-flex p-0">
                    <h3 class="card-title p-3 fa fa-id-card"> Subject Combintion</h3>
                    <ul class="nav nav-pills ml-auto p-2">
                        @* tab-1 *@
                        <li class="nav-item">
                            <a class="nav-link  active" href="#subtab_1" data-toggle="tab">
                                <i class="fa fa-leaf"></i>&nbsp;Secondary
                            </a>
                        </li>

                        @* tab-2 *@
                        <li class="nav-item">
                            <a class="nav-link" href="#subtab_2" data-toggle="tab">
                                <i class="fa fa-leaf"></i>&nbsp;Higher Secondary
                            </a>
                        </li>
                    </ul>
                </div><!-- /.card-header -->
                <div class="card-body">
                    <div class="tab-content p-3">
                        <div class="tab-pane active" id="subtab_1">
                            @{
                               var actionData=  Html.Action("MpSubCombCreate");
                            }
                            @actionData
                        </div>

                        <div class="tab-pane active" id="subtab_2">

                        </div>
                        <!-- /.tab-pane -->


                    </div>
                    <!-- /.tab-content -->
                </div><!-- /.card-body -->
            </div>
            <!-- ./card -->
        </div>
        <!-- /.col -->
    </div>


</div>

SP.Web/Areas/Subject/Views/SubjectsCombinations/MpSubCombCreate.cshtml
@model SP.Data.Models.MPSubjectsCombination
@using SP.Web.Infrastructure.AjaxStructure
@using SP.Data.Models
@{
    /**/

    ViewBag.Title = "";
    Layout = null;
}

<div id="replace-this" class="container-fluid">

            @{ using (Ajax.BeginForm("MpSubCombCreate", "SubjectsCombinations",
                  new AjaxOptions { HttpMethod = "POST", InsertionMode = InsertionMode.Replace, UpdateTargetId = "replace-this", LoadingElementId = AjaxFormIStruct.AjaxBeginFormLoading }))
                {
                   @Html.AntiForgeryToken()

                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="col-md-12 card card-danger  card-outline ">
                        <div class="card-header"><div class="card-title">Group Details</div></div>
                        <div class="card-body row">
                            <div class=" col-md-6 form-group">
                                @Html.LabelFor(model => model.GroupId, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.DropDownList("GroupId", (SelectList)ViewBag.GroupId, new { onchange = "$('#btnPostBackView').click();", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.GroupId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class=" col-md-6 form-group">
                                @Html.LabelFor(model => model.ClassId, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.DropDownList("ClassId", (SelectList)ViewBag.ClassId, new { onchange = "$('#btnPostBackView').click();", @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.ClassId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            @* use for post back the DropDownList *@
                            <input type="submit" value="postBack" id="btnPostBackView" name="btnPostBackView" style="display:none" />
                        </div>
                    </div>

                    <div class="col-md-12 card card-info card-outline">
                        <div class="card-header"><div class="card-title">Subject Details</div></div>
                        <div class="card-body row">
                            <div class=" col-md-6 form-group">
                                @Html.LabelFor(model => model.SubjectId, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.DropDownList("SubjectId", (SelectList)ViewBag.SubjectId, htmlAttributes: new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.SubjectId, "", new { @class = "text-danger" })
                                </div>
                            </div>

                            <div class="col-md-4 form-group">
                                @Html.LabelFor(model => model.SubjectType, htmlAttributes: new { @class = "control-label" })
                                <div class="">
                                    @Html.DropDownListFor(model => model.SubjectType, new List<SelectListItem>
                             () { new SelectListItem() { Text = "Main", Value = "Main" }, new SelectListItem() { Text = "Optional", Value = "Optional" } }, new { @class = "form-control" })
                                    @Html.ValidationMessageFor(model => model.SubjectType, "", new { @class = "text-danger" })
                                </div>
                            </div>


                            <div class=" col-md-2 form-group align-middle">
                                <div class="col-md-offset-2 ">
                                    <br />
                                    <input type="submit" id="btnAddSubCombination" name="btnAddSubCombination" value="Create" class="btn btn-default bg-primary-gradient pull-right" />
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="col-md-12 card card-info card-outline">
                        <div class="card-header"><div class="card-title"></div></div>
                        <div class="card-body">
                            <table class="table">
                                <thead>
                                    <tr>
                                        <th>
                                            @Html.DisplayNameFor(model => model.MPSubject.SubjectName)
                                        </th>
                                        <th>
                                            @Html.DisplayNameFor(model => model.SubjectType)
                                        </th>
                                        <th><i class="fa fa-pencil"></i></th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @{
                                        var subCombinationData = (List<MPSubjectsCombination>)ViewBag.lstMpSubjectsCombinations;
                                        if (subCombinationData != null)
                                        {

                                            foreach (var item in subCombinationData)
                                            {
                                                <tr>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.MPSubject.SubjectName)
                                                    </td>
                                                    <td>
                                                        @Html.DisplayFor(modelItem => item.SubjectType)
                                                    </td>

                                                    <td>
                                                        <input type="submit" id="btnDelete" name="btnDelete" value=@item.Id class="btn btn-default" />

                                                        @Html.ActionLink(" ", "DeleteMpCombinationSubject",
                                                             new { SubID = item.Id, GrpId = Model.GroupId }, new { @class = "fa fa-close w3-hover-text-red" })
                                                    </td>
                                                </tr>
                                            }
                                        }
                                    }
                                </tbody>
                            </table>
                        </div>
                    </div>


                }
            }
        </div>